AWSTemplateFormatVersion: "2010-09-09"
Description: This is the CFT for launching .
Resources:
  MyTestVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16  
      EnableDnsHostnames: true
      Tags:
          - Key: Testing_purpose
            Value: "AWSTestVPC"

